import type { Task, BoundingBox, Telemetry } from '../types';

export const INITIAL_TELEMETRY: Telemetry = {
  npuLatencyMs: 32,
  cloudEgressBytes: 0,
  modelSTT: 'Whisper-Tiny (INT4 Quantized)',
  modelLLM: 'Gemma-2B-IT (Local NPU)',
  quantization: 'W4A16 Q-Engine',
  ocrAccuracy: '98.4%',
  throughputTokensPerSec: 68.4,
};

export const INITIAL_BOUNDING_BOXES: BoundingBox[] = [
  {
    id: 'box-1',
    label: 'Client Traffic Ingress',
    x: 4,
    y: 18,
    width: 20,
    height: 44,
    confidence: 0.99,
    color: '#06B6D4',
  },
  {
    id: 'box-2',
    label: 'Auth Gateway (Envoy / Node)',
    x: 28,
    y: 15,
    width: 28,
    height: 50,
    confidence: 0.98,
    color: '#FF7A00',
  },
  {
    id: 'box-3',
    label: 'Redis Token Bucket Store',
    x: 62,
    y: 10,
    width: 34,
    height: 34,
    confidence: 0.97,
    color: '#10B981',
  },
  {
    id: 'box-4',
    label: 'PostgreSQL User DB Cluster',
    x: 62,
    y: 52,
    width: 34,
    height: 40,
    confidence: 0.96,
    color: '#8B5CF6',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-init-01',
    title: 'Audit mobile P2P transport latency over Wi-Fi Direct',
    description: 'Ensure Office Kit zero-copy frame buffer sync maintains < 50ms transfer times for uncompressed voice frames.',
    status: 'in_progress',
    priority: 'high',
    assignee: {
      name: 'Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
      role: 'Firmware & Transport Lead',
    },
    source: 'voice',
    sourceLabel: '[Voice Memo]',
    tags: ['#office-kit', '#transport', '#p2p'],
    createdAt: '10 mins ago',
    timeEstimate: '3h',
    confidenceScore: 0.97,
  },
  {
    id: 'task-init-02',
    title: 'Quantize Gemma-2B IT model weights to INT4 for Snapdragon NPU',
    description: 'Benchmark offline inference throughput on hex-core NPU. Verify zero degradation on structured JSON extraction format.',
    status: 'in_progress',
    priority: 'high',
    assignee: {
      name: 'Alex Rivera',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face',
      role: 'AI / Edge Lead',
    },
    source: 'whiteboard',
    sourceLabel: '[Whiteboard]',
    tags: ['#npu', '#gemma2b', '#int4'],
    createdAt: '25 mins ago',
    timeEstimate: '5h',
    confidenceScore: 0.99,
  },
  {
    id: 'task-init-03',
    title: 'Design high-contrast visual tokens for dark mode developer HUD',
    description: 'Establish electric orange (#FF7A00) accent hierarchy, glassmorphism border rules (border-white/10), and crisp typography.',
    status: 'done',
    priority: 'medium',
    assignee: {
      name: 'Elena Rostova',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
      role: 'Staff Product Designer',
    },
    source: 'manual',
    sourceLabel: '[Manual Sync]',
    tags: ['#design-system', '#tokens', '#hud'],
    createdAt: '1 hour ago',
    timeEstimate: '2h',
    confidenceScore: 1.0,
  },
  {
    id: 'task-init-04',
    title: 'Setup end-to-end air-gapped cryptographic signing for context drops',
    description: 'Validate Ed25519 payload signatures generated on iQOO 13 secure element before desktop client commits tasks to local store.',
    status: 'todo',
    priority: 'medium',
    assignee: {
      name: 'Marcus Dev',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&h=100&fit=crop&crop=face',
      role: 'Security Engineer',
    },
    source: 'whiteboard',
    sourceLabel: '[Whiteboard]',
    tags: ['#security', '#ed25519', '#offline'],
    createdAt: '2 hours ago',
    timeEstimate: '4h',
    confidenceScore: 0.94,
  },
];

export const INITIAL_MARKDOWN_PRD = `# PRD: Distributed Authentication & Resilient Rate Limiter
**Generated By**: ContextSnap Offline Engine (iQOO 13 On-Device SLM)
**Author Engine**: Gemma-2B-IT (Quantized INT4) • Local Latency: 32ms
**Security Boundary**: 100% Air-Gapped / Zero Cloud Egress

---

## 1. Executive Summary
During the mobile whiteboard sync session via Office Kit, the architecture team sketched a resilient token bucket rate limiter directly upstream of our authentication service. The system must throttle abusive credential-stuffing attempts while guaranteeing sub-5ms lookup latency for legitimate developer traffic.

---

## 2. Architecture Diagram

\`\`\`mermaid
flowchart LR
    Client([Public Clients]) -->|HTTPS Requests| Envoy["Auth Gateway (Envoy)"]
    Envoy -->|Check Quota| Redis[("Redis Token Bucket")]
    Redis -->|Allowed (200)| Envoy
    Redis -.->|Throttled (429)| Envoy
    Envoy -->|Route Request| AuthService["Internal Auth Microservice"]
    AuthService -->|Read / Write| Postgres[("User DB Cluster")]

    classDef gateway fill:#1e293b,stroke:#ff7a00,stroke-width:2px,color:#fff;
    classDef storage fill:#0f172a,stroke:#06b6d4,stroke-width:2px,color:#fff;
    class Envoy gateway;
    class Redis,Postgres storage;
\`\`\`

---

## 3. Technical Specifications & Quota Rules

| Route Target | Limit Window | Burst Capacity | Storage Backend | Action on Exceed |
| :--- | :--- | :--- | :--- | :--- |
| \`/api/v1/auth/login\` | 5 req / sec | 10 requests | Redis In-Memory Cluster | HTTP 429 + Retry-After |
| \`/api/v1/auth/refresh\` | 20 req / sec | 40 requests | Redis Replica | HTTP 429 |
| \`/api/v1/auth/register\` | 2 req / min | 3 requests | Redis In-Memory Master | HTTP 429 + Captcha Challenge |

---

## 4. Key Implementation Checklist
- [x] Transmit architecture schema via iQOO 13 Office Kit P2P Wi-Fi Direct.
- [ ] Implement sliding window token bucket algorithm using atomic Redis EVAL Lua script.
- [ ] Inject \`X-RateLimit-Limit\`, \`X-RateLimit-Remaining\`, and \`X-RateLimit-Reset\` response headers.
- [ ] Export Prometheus counter metrics (\`ratelimit_requests_total{status="rejected"}\`).
`;

export const SCENARIO_A_AUDIO_TRANSCRIPT = 
  "Hey team, we need to implement the rate limiter on the auth route by Friday, assigned to Alex.";

export const SCENARIO_A_TASK: Task = {
  id: 'task-voice-alex-auth',
  title: 'Implement token bucket rate limiter on /api/v1/auth',
  description: 'Enforce strict 5 req/sec burst limit per client IP on authentication routes to prevent credential brute-forcing. Synchronize with Redis cluster.',
  status: 'todo',
  priority: 'high',
  assignee: {
    name: 'Alex Rivera',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face',
    role: 'AI / Edge Lead',
  },
  source: 'voice',
  sourceLabel: '[Voice Memo]',
  tags: ['#auth', '#ratelimit', '#security', '#p0'],
  createdAt: 'Just now',
  timeEstimate: '4h',
  dueDate: 'Friday 5:00 PM',
  confidenceScore: 0.99,
  highlighted: true,
};

export const SCENARIO_B_TASKS: Task[] = [
  {
    id: 'task-wb-redis-01',
    title: 'Provision Redis Token Bucket Cluster & Atomic Lua Scripts',
    description: 'Extracted from Whiteboard Node [Redis Token Bucket Store]: configure in-memory key expiration with atomic sliding window rate check.',
    status: 'todo',
    priority: 'high',
    assignee: {
      name: 'Sarah Chen',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
      role: 'Firmware & Transport Lead',
    },
    source: 'whiteboard',
    sourceLabel: '[Whiteboard]',
    tags: ['#redis', '#architecture', '#tokens'],
    createdAt: 'Just now',
    timeEstimate: '6h',
    confidenceScore: 0.98,
    highlighted: true,
  },
  {
    id: 'task-wb-envoy-02',
    title: 'Configure Envoy API Gateway rate_limit HTTP filter',
    description: 'Extracted from Whiteboard Node [Auth Gateway]: configure global ratelimit descriptor domain and route matcher in envoy.yaml.',
    status: 'todo',
    priority: 'high',
    assignee: {
      name: 'Alex Rivera',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face',
      role: 'AI / Edge Lead',
    },
    source: 'whiteboard',
    sourceLabel: '[Whiteboard]',
    tags: ['#envoy', '#gateway', '#filter'],
    createdAt: 'Just now',
    timeEstimate: '4h',
    confidenceScore: 0.97,
    highlighted: true,
  },
  {
    id: 'task-wb-telemetry-03',
    title: 'Implement 429 Prometheus Metrics & Observability exporter',
    description: 'Extracted from Whiteboard Ingress & DB boundaries: log throttled requests, client IPs, and Grafana dashboard alerts.',
    status: 'in_progress',
    priority: 'medium',
    assignee: {
      name: 'Marcus Dev',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&h=100&fit=crop&crop=face',
      role: 'Security Engineer',
    },
    source: 'whiteboard',
    sourceLabel: '[Whiteboard]',
    tags: ['#metrics', '#prometheus', '#grafana'],
    createdAt: 'Just now',
    timeEstimate: '3h',
    confidenceScore: 0.95,
    highlighted: true,
  },
];
